from enum import Enum


class ErrorCode(str, Enum):
    DOMAIN_ALREADY_EXIST = "DOMAIN_ALREADY_EXIST"
    INTERNAL_SERVER_ERROR = "INTERNAL_SERVER_ERROR"
    DNS_SERVER_ERROR = "DNS_SERVER_ERROR"

    INVALID_GOOGLE_CREDENTIALS = "INVALID_GOOGLE_CREDENTIALS"
    INVALID_SESSION = "INVALID_SESSION"
    SESSION_NOT_VERIFIED = "SESSION_NOT_VERIFIED"

    DOMAIN_NOT_ALLOWED = "DOMAIN_NOT_ALLOWED"
